# revive configuration
# https://github.com/mgechev/revive

ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.blank-imports]

[rule.context-as-argument]

[rule.context-keys-type]

[rule.dot-imports]

[rule.error-return]

[rule.error-strings]

[rule.error-naming]

[rule.exported]
  arguments = ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

[rule.if-return]

[rule.increment-decrement]

[rule.var-naming]
  arguments = [["ID", "URL", "HTTP", "API", "JSON", "XML", "SQL", "DB", "ENV", "CLI", "YAML", "YML"], []]

[rule.var-declaration]

[rule.package-comments]

[rule.range]

[rule.receiver-naming]

[rule.indent-error-flow]

[rule.errorf]

[rule.empty-block]

[rule.superfluous-else]

[rule.unused-parameter]
  arguments = [{ allowRegex = "^_" }]

[rule.unreachable-code]

[rule.redefines-builtin-id]

[rule.add-constant]
  arguments = [{ maxLitCount = "3", allowStrs = "\"\"", allowInts = "0,1,2", allowFloats = "0.0,1.0" }]

[rule.argument-limit]
  arguments = [5]

[rule.cognitive-complexity]
  arguments = [15]

[rule.cyclomatic]
  arguments = [15]

[rule.early-return]

[rule.empty-lines]

[rule.function-result-limit]
  arguments = [3]

[rule.identical-branches]

[rule.unnecessary-stmt]

[rule.useless-break]
