// Package constants provides shared constants used across the application.
package constants

// File and directory permissions.
const (
	DirPermissions  = 0o755
	FilePermissions = 0o644
)

// Configuration file names and paths.
const (
	ConfigDir       = ".tasker"
	ConfigFile      = "config.yml"
	TasksDir        = ".tasker/tasks"
	SchemasDir      = ".tasker/schemas"
	TaskfileOutput  = "Taskfile.yml"
	MakefileOutput  = "Makefile"
	TaskSchemaFile  = "tasker.schema.json"
	TasksSchemaFile = "tasks.schema.json"
)

// Generated file header lines.
const (
	HeaderGenerated = "# Generated by Tasker - DO NOT EDIT"
	HeaderSource    = "# Source: .tasker/config.yml + .tasker/tasks/*.yml"
	HeaderRegenerate = "# Regenerate with: tasker generate"
)
